### DISCUSSION TITLE
[Question] Problems with access via Cloudflare tunnel

### DISCUSSION THREAD

**Discussion by rwbronco** [schlagmichdoch/PairDrop#272] [General]
My pairdrop stopped working recently, so I updated to the most recent version.

Using Docker on Windows.

My issue is that it works just fine on 127.0.0.1:3000, but if I go to the domain that it's accessible at via Cloudflare tunnel, the "You are known as:" just sits at "loading," and none of the buttons in the top right are clickable except light/dark mode.

pairdrop.net works fine on all devices.

I've clearly got an issue where I've not declared my domain/subdomain somewhere and it's not fully connecting. Has something changed that could be causing this? Here's my docker compose:

```
version: "2"
services:
    pairdrop:
        image: lscr.io/linuxserver/pairdrop:latest
        container_name: pairdrop
        restart: unless-stopped
        environment:
            - PUID=1000 # UID to run the application as
            - PGID=1000 # GID to run the application as
            - WS_FALLBACK=false # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
            - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
            - TZ=America/Chicago # Time Zone
        ports:
            - 127.0.0.1:3000:3000 # Web UI
```
