### DISCUSSION TITLE
Devices cannot see each other over the internet?

### DISCUSSION THREAD

**Discussion by Giraffaman** [schlagmichdoch/PairDrop#360] [Q&A]
So far I've only been able to get devices to see each other if they are in the same subnet. As soon as I connect over the internet with or without VPN, my devices stop seeing each other.

This is what I've tried:
- pair devices - once connecting via the internet, both devices still show they're paired, but they do not see each other
- put devices in the same room - same behavior as with pairing
- use a VPN (wireguard) which puts my devices onto the same network, but on different subnets
- enable fallback to websockets

Pairdrop sits behind a reverse proxy (nginx proxy manager) but with no special config and Websockets are enabled:
![image](https://github.com/user-attachments/assets/04fac5a6-983a-48d9-ba6e-8ea7fe76ed69)
![image](https://github.com/user-attachments/assets/48cc67da-ce52-4ffa-97e7-c46cbe670bbb)
![image](https://github.com/user-attachments/assets/b2da3875-be68-46b8-b540-a1e02f2cecf8)
![image](https://github.com/user-attachments/assets/91975451-45bf-4e4d-b9c2-c1b43026b039)

This is the docker compose config I am using (basically just copied from the docs for testing):
```
version: "3"
services:
    pairdrop:
        image: "lscr.io/linuxserver/pairdrop:latest"
        container_name: pairdrop
        restart: unless-stopped
        environment:
          - PUID=1000 # UID to run the application as
          - PGID=1000 # GID to run the application as
          - WS_FALLBACK=false # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
          - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
          - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers.
          - DEBUG_MODE=true # Set to true to debug container and peer connections.
          - TZ=Etc/UTC # Time Zone
        ports:
          - "9476:3000" # Web UI
        networks:
          - bay-21-internal

networks:
  bay-21-internal:
    external: true
    name: bay-21-internal
```

Debug log:
- 10.0.0.55 is my docker host
- 41.66.99.34 is my phone over mobile connection
- 10.0.0.253 is my router
- first attempt was internet no VPN, second was with VPN, third was over Wifi no VPN
```
----DEBUGGING-PEER-IP-START----
remoteAddress: ::ffff:10.0.0.55
x-forwarded-for: 41.66.99.34
cf-connecting-ip: undefined
PairDrop uses: 41.66.99.34
IP is private: false
if IP is private, '127.0.0.1' is used instead
----DEBUGGING-PEER-IP-END----
----DEBUGGING-PEER-IP-START----
remoteAddress: ::ffff:10.0.0.55
x-forwarded-for: 10.0.0.253
cf-connecting-ip: undefined
PairDrop uses: 10.0.0.253
IP is private: true
if IP is private, '127.0.0.1' is used instead
----DEBUGGING-PEER-IP-END----
----DEBUGGING-PEER-IP-START----
remoteAddress: ::ffff:10.0.0.55
x-forwarded-for: 10.0.0.253
cf-connecting-ip: undefined
PairDrop uses: 10.0.0.253
IP is private: true
if IP is private, '127.0.0.1' is used instead
----DEBUGGING-PEER-IP-END----
```

What am I doing wrong here or what else can I check? This service works great for file transfers over the wifi but it would be cool to get it working over the internet (or at least using VPN).

Any hints would be greatly appreciated.
