### ISSUE TITLE
[Bug] Cross device Peers are not discoverable

### ISSUE THREAD

**Issue by vedhavyas** [schlagmichdoch/PairDrop#215]
**Describe the bug**
I'm able to see each other peers between two macs but when I open it on mobile browser, mobile peer is not shown even though I can see peer connected through logs. Also, I'm able to pair the mac and android as well and it doesn't show up. I see the attached screenshot on android and on mac under peer list, android peer also shows undefined.

**Expected behavior**
I expected peer from android is showed up on macs and vice-verse

**Screenshots**
![pairdrop_error](https://github.com/schlagmichdoch/PairDrop/assets/7549475/c211c1df-437a-4cee-b11b-06a628360804)

**Smartphone (please complete the following information):**
 - Device: Nothing Phone
 - OS: Android 13
 - Browser: Brave
 - Version: 1.61.100

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No
Version: v1.9.4

**Bug occurs on self-hosted PairDrop instance**
Yes

**Self-Hosted Setup**
Proxy: Caddy
Deployment: docker-compose 
Version: v1.9.4

**Additional context**
I have a vpn and all the services are under this vpn

**Comment by schlagmichdoch** [comment]
If this only happens on your self hosted instance: Have you setup a TURN server for PairDrop? This is needed for some cross-device connections to work

**Comment by schlagmichdoch** [comment]
It may be, that your VPN blocks WebRTC completely. Can you try to switch it off or check if there is an option for allowing WebRTC?

Your devices must be able to create WebRTC connections to be able to use PairDrop. 

Visit this page with your device to check if WebRTC is supported: 
https://www.webrtc-experiment.com/DetectRTC/#isWebRTCSupported

Next to `Browser Supports WebRTC (Either 1.0 or 1.1)?` it must say `Yep`. Some networks or VPN connections somehow disable all WebRTC connections.

You can also try to use pairdrop.net with your VPNs enabled. If this breaks the functionality, probably your VPN is blocking WebRTC

**Comment by vedhavyas** [comment]
> Visit this page with your device to check if WebRTC is supported:
[webrtc-experiment.com/DetectRTC/#isWebRTCSupported](https://www.webrtc-experiment.com/DetectRTC/#isWebRTCSupported)

It does say `Yep` so it must be supporting

>You can also try to use pairdrop.net with your VPNs enabled. If this breaks the functionality, probably your VPN is blocking WebRTC

It works on pairdrop.net but not my self hosted one

Any ideas how I can debug this ?

**Comment by vedhavyas** [comment]
> To make deploying a TURN server alongside PairDrop the docs will be updated in v1.10.0. This will be deployed later today but you can also find it here:

I have already deployed coturn alsong side the pairdrop. This is how my docker compose looks like
```
pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    hostname: pairdrop
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
      - WS_FALLBACK=true
      - DEBUG_MODE=true
      - RTC_CONFIG=/etc/pairdrop/rtc_config.json
    networks:
      - docker-direct
    volumes:
      - $CONF_DIR/rtc_config.json:/etc/pairdrop/rtc_config.json
    labels:
      caddy: pairdrop.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

  turnserver:
    image: coturn/coturn:latest
    container_name: turnserver
    hostname: turnserver
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - $CONF_DIR/turnserver.conf:/etc/coturn/turnserver.conf
      - "${DATA_DIR}/turnserver/data/:/var/db/"
      - "${DATA_DIR}/turnserver/log:/var/log/"
      - "${DATA_DIR}/turnserver/run:/var/run/"
    networks:
      docker-direct:
        ipv4_address: 10.10.2.10
    expose:
      - "10000-20000"
    labels:
      caddy: turnserver.hub
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3478}}"
```

Here are my configs for coturn and pairdrop respectively
```
# TURN server name and realm
realm=turnserver.hub
server-name=turnserver.hub

# Use fingerprint in TURN message
fingerprint

# IPs the TURN server listens to
listening-ip=0.0.0.0

# Main listening port
listening-port=3478

# Further ports that are open for communication
min-port=10000
max-port=20000

# Log file path
log-file=/var/log/turnserver.log

# Enable verbose logging
verbose

# sqlite
userdb=/var/db/turndb
```
```
{
  "sdpSemantics": "unified-plan",
  "iceServers": [
    {
      "urls": "turn:turnserver:3478"
    }
  ]
}
```

> Also, have you tried using other browsers than Brave?

I will in different browsers and get back on this
