### ISSUE TITLE
[Bug] Buttons do not change color on hover

### ISSUE THREAD

**Issue by schlagmichdoch** [schlagmichdoch/PairDrop#262]
**Describe the bug**
Buttons should change on hover, but they do not

**Screenshots**
https://imgur.com/a/tA6x1oz

**Bug occurs on official PairDrop instance https://pairdrop.net/**
Yes
Version: v1.10.6

**Bug occurs on self-hosted PairDrop instance**
Yes

**Solution**
Opacity changes in background for icon-buttons but in foreground for all other buttons
```css
.icon-button::before {
    z-index: -1;
}

.btn::before {
    z-index: 0; /*default*/
}
```
