### ISSUE TITLE
[Bug] Chromebook only works with Android in self-hosted

### ISSUE THREAD

**Issue by jl-678** [schlagmichdoch/PairDrop#363]
**Describe the bug**
I run a self-hosted instance of Pairdrop, and it works great except for with my Chromebook. I have tested with numerous Mac, Windows, Android and iOS devices and all are recognized properly. Strangely, my Chrome can ONLY be discovered by my Android phone and nothing else. (To be clear discovery is bi-directional - my phone sees the Chromebook and everything else while my Chromebook sees my phone and nothing else.) I have tested this with two different browsers (Chrome & DuckDuck Go) on the Chromebook with the same behavior.

**To Reproduce**
Connect devices to the local Pairdrop instance and the Chrombook never appears except on my phone

**Expected behavior**
The Chrombook should appear normally like every other device

**Screenshots**
I think that the problem is self explanatory

**Desktop (please complete the following information):**
 - OS: ChromeOS: 132.0.6834.94
 - Browser: Chome and DuckDuckGo
 - Version: 132.0.6834.94

**Bug occurs on official PairDrop instance https://pairdrop.net/**
No

**Bug occurs on self-hosted PairDrop instance**
Yes

**Self-Hosted Setup**
Proxy: Nginx Proxy Manager
Deployment: Docker compose
Version: v1.10.10

Docker compose for reference:
```
version: "3"
services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=1000 # UID to run the application as
      - PGID=1000 # GID to run the application as
      - WS_FALLBACK=true # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=false # Set to true to debug container and peer connections.
      - TZ=<local TZ> # Time Zone
    ports:
      - "<private_IP>:7000:3000"
```

**Additional context**
All devices are using Chrome.
